//
// Created by cayun on 2019-03-15.
//

#ifndef YYL_BRIDGE_EXCEPTION_H
#define YYL_BRIDGE_EXCEPTION_H

#define SERVER_SOCKET_CREATE_ERROR -1
#define SERVER_SOCKET_BIND_ERROR -2
#define SERVER_SOCKET_LISTEN_ERROR -3

#endif //YYL_BRIDGE_EXCEPTION_H
