//
// Created by cayun on 2019-03-15.
//

#ifndef MZZ_BRIDGE_C_EXCEPTION_H
#define MZZ_BRIDGE_C_EXCEPTION_H

#define SERVER_SOCKET_CREATE_ERROR -1
#define SERVER_SOCKET_BIND_ERROR -2
#define SERVER_SOCKET_LISTEN_ERROR -3

#endif //MZZ_BRIDGE_C_EXCEPTION_H
